# Generated by Django 3.2.9 on 2021-11-22 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_alter_animal_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='animal',
            name='image',
            field=models.ImageField(max_length=400, null=True, upload_to=''),
        ),
    ]
