# Generated by Django 3.2.9 on 2021-11-22 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_alter_animal_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='animal',
            options={'ordering': ('name',)},
        ),
    ]
